language: python
python:
- '3.6'
addons:
  mariadb: '10.0'
before_install:
  - mysql -e 'CREATE DATABASE production;'
install: pip install -r src/requirements.txt
script: py.test --cov=./
after_success:
  - codecov
